- name: Automatisation complète K3d
  hosts: localhost
  tasks:
    - name: Nettoyage des anciens déploiements
      shell: |
        kubectl delete deployment nginx-custom --ignore-not-found
        kubectl delete svc nginx-custom --ignore-not-found

    - name: Création du Deployment avec ton image Packer
      shell: |
        kubectl create deployment nginx-custom --image=mon-nginx-custom:v1

    - name: Exposition du Service sur un port fixe (NodePort)
      shell: |
        kubectl expose deployment nginx-custom --port=80 --target-port=80 --type=NodePort --overrides='{"spec": {"ports": [{"nodePort": 30080, "port": 80, "targetPort": 80}]}}'
